// The runtime Sorb config for the admin (mirrors sorb-demo/src/sorbConfig.js pattern).
// Sorb is the ENGINE (token delivery via SorbProvider + CSS custom properties); the Primer
// primitive set is the PAINT. tokens.js is generated by `pnpm run tokens` (Style Dictionary).
import tokens from './tokens/generated/tokens.js'

/** @type {import('@sorb/leaf').SorbConfig} */
export const sorbConfig = {
  namespace: 'fls-admin',
  tokens, // committed set — production values AND the preview fallback
  preview: {
    // off unless explicitly enabled; localhost-only origin by default (leaf's allowlist).
    // This is the dogfood beat: `sorb dev` + the Figma plugin can re-skin this admin live.
    enabled: import.meta.env.DEV,
  },
}
