// Style Dictionary config — the Sorb pipeline's build half for admin-v2.
// Two DTCG tiers (primitive → semantic) merge; two outputs:
//   variables.css — the CSS custom properties components read via var(--token, fallback)
//   tokens.js     — flat TokenSet for @sorb/leaf's SorbProvider (the committed set)
// Pattern borrowed from sorb-demo/sd.config.js, trimmed to the two platforms P0 needs.
import StyleDictionary from 'style-dictionary'

// Flat { 'color-accent': '#0969da', ... } module for SorbProvider (mirrors sorb-demo's
// SORB_TOKENSET format without the extra sorb metadata platforms).
StyleDictionary.registerFormat({
  name: 'fls/tokenset',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map((t) => `  '${t.name}': '${t.$value ?? t.value}',`)
      .join('\n')
    return `// generated by sd.config.js — do not edit\nexport default {\n${entries}\n}\n`
  },
})

/** @type {import('style-dictionary').Config} */
export default {
  source: ['tokens/primitive.json', 'tokens/semantic.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/tokens/generated/',
      files: [
        { destination: 'variables.css', format: 'css/variables', options: { outputReferences: true } },
      ],
    },
    js: {
      transformGroup: 'css', // kebab names so tokens.js keys match the css platform's var names
      buildPath: 'src/tokens/generated/',
      files: [{ destination: 'tokens.js', format: 'fls/tokenset' }],
    },
  },
}
